"""The agent-credential keyset — the ONE enumerated list the wizard manages.

This is the exact set of keys the wizard manages (and that `shimpz-app`'s `_deploy_secretgate`
forbids to project apps). Installer-owned control-plane credentials may coexist in `.env`, but are
never exposed as wizard fields. The wizard renders the form FROM this list and the API does exact
lookups AGAINST it — an unknown key is a hard error, never a silent write (fail-fast doctrine).
Machine-internal secrets carry `generate: True` and are minted here, never typed by a human.

`validator` values are dispatched by validate_live.py: a `live_*` kind performs one real remote
call; a `re:` kind is a full-match regex; None means presence-only.
"""

import secrets

# Field order here IS the form order and the .env render order.
SCHEMA = (
    # ── machine-internal (generated, never asked) ────────────────────────────────────────────
    {
        "key": "POSTGRES_PASSWORD",
        "group": "internal",
        "required": True,
        "generate": True,
        "secret": True,
        "validator": None,
        "help": "PostgreSQL superuser password — generated by the wizard, consumed only by pg-driver.",
    },
    # ── Cloudflare R2 (uploads / links / backup) ─────────────────────────────────────────────
    {
        "key": "R2_ACCOUNT_ID",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[0-9a-f]{32}",
        "help": "R2 account ID (hex, from the S3 endpoint).",
    },
    {
        "key": "R2_ACCESS_KEY_ID",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "re:[0-9a-f]{16,64}",
        "help": "R2 access key (scoped to one bucket).",
    },
    {
        "key": "R2_SECRET_ACCESS_KEY",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "re:[0-9a-f]{32,128}",
        "help": "R2 secret key.",
    },
    {
        "key": "R2_BUCKET",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[a-z0-9][a-z0-9-]{1,61}[a-z0-9]",
        "help": "Bucket name the token is scoped to.",
    },
    # ── desktop / advanced ───────────────────────────────────────────────────────────────────
    {
        "key": "KASM_USER",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": None,
        "help": "Optional extra basic-auth layer on the KasmVNC desktop.",
    },
    {
        "key": "KASM_PASSWORD",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": None,
        "help": "Optional (pairs with KASM_USER).",
    },
    {
        "key": "SHIMPZ_SIGNUP_ENABLED",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[01]",
        "help": "Public signup switch: 1 allows new accounts (default); 0 disables new registrations.",
    },
    {
        "key": "DOCKER_GID",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:\\d{1,6}",
        "help": "Host docker group id (must match `stat -c '%g' /var/run/docker.sock`; default 989).",
    },
    {
        "key": "SHIMPZ_TEAM_MAX_HTTP_CONCURRENCY",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[1-9][0-9]*",
        "help": "Maximum simultaneous Team control-plane requests (default 64; must be positive).",
    },
    {
        "key": "SHIMPZ_TEAM_HTTP_CONNECTION_TIMEOUT_SECONDS",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[1-9][0-9]*",
        "help": "Team control-plane socket timeout in seconds (default 30; must be positive).",
    },
    {
        "key": "SHIMPZ_SUFFIX",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:-[a-z0-9]{1,10}",
        "help": "Multi-instance suffix (e.g. -t) — leave EMPTY on the primary instance. Names every "
        "container/network/volume so two agents coexist on one machine.",
    },
    {
        "key": "SHIMPZ_DATA",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:/[A-Za-z0-9._/-]+",
        "help": "Host data dir bound to /config (default /opt/shimpz; a second instance needs its own, "
        "e.g. /opt/shimpz-t).",
    },
    {
        "key": "CHROME_EXTRA_ARGS",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": None,
        "help": "Normally empty. Set --no-sandbox only if the host kernel denies user namespaces.",
    },
)

BY_KEY = {f["key"]: f for f in SCHEMA}

# Per-credential acquisition guide — the wizard renders this as an expandable, numbered
# "How to get this →" with a direct link to the provider. Only the credentials a human must
# actually hunt for get an entry; generated/advanced keys rely on their one-line `help`.
GUIDES = {
    "R2_ACCOUNT_ID": {
        "link": "https://dash.cloudflare.com/?to=/:account/r2",
        "link_label": "Cloudflare → R2",
        "steps": [
            "Open Cloudflare → R2. The Account ID (hex) is shown in the S3 API endpoint.",
            "Create a bucket first if you don’t have one (put its name in R2_BUCKET below).",
            "Optional — R2 is for uploads, share links and backups.",
        ],
    },
    "R2_ACCESS_KEY_ID": {
        "link": "https://dash.cloudflare.com/?to=/:account/r2/api-tokens",
        "link_label": "Cloudflare → R2 → API Tokens",
        "steps": [
            "In R2 → Manage API Tokens, create an Account API token with Object Read & Write, scoped to your bucket.",
            "Copy the Access Key ID here and the Secret Access Key into the next field.",
        ],
    },
}


def field(key):
    """Exact lookup; unknown key raises (the fail-fast contract every caller relies on)."""
    try:
        return BY_KEY[key]
    except KeyError:
        raise ValueError(f"unknown key {key!r} — not in the agent keyset") from None


def generate_internal(existing):
    """Mint values for `generate` keys that are absent/empty in `existing` → {key: new_value}.

    Never overwrites a present value (rotation is a deliberate act, not a side effect).
    """
    return {
        f["key"]: secrets.token_urlsafe(24) for f in SCHEMA if f["generate"] and not existing.get(f["key"], "").strip()
    }
