"""The agent-credential keyset — the ONE enumerated list the wizard manages.

This is the exact set of keys `.env` holds (and that `shimpz-app`'s `_deploy_secretgate` forbids to
project apps). The wizard renders the form FROM this list and the API does exact lookups AGAINST
it — an unknown key is a hard error, never a silent write (fail-fast doctrine). Machine-internal
secrets carry `generate: True` and are minted here, never typed by a human.

`validator` values are dispatched by validate_live.py: a `live_*` kind performs one real remote
call; a `re:` kind is a full-match regex; None means presence-only.
"""

import secrets

# Field order here IS the form order and the .env render order.
SCHEMA = (
    # ── machine-internal (generated, never asked) ────────────────────────────────────────────
    {
        "key": "POSTGRES_PASSWORD",
        "group": "internal",
        "required": True,
        "generate": True,
        "secret": True,
        "validator": None,
        "help": "PostgreSQL superuser password — generated by the wizard, consumed only by pg-driver.",
    },
    {
        "key": "REDPANDA_ADMIN_PASSWORD",
        "group": "internal",
        "required": True,
        "generate": True,
        "secret": True,
        "validator": None,
        "help": "Redpanda SASL superuser — generated by the wizard; held by broker bootstrap, init, and bus-driver.",
    },
    # ── Cloudflare (optional — enables publishing on your domains; cf-driver boots inert
    #    with an empty token, ops fail lazily at call time, same as R2/OpenAI) ──────────────────
    {
        "key": "SHIMPZ_CF_TOKEN",
        "group": "cloudflare",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "live_cloudflare",
        "help": "Cloudflare API token (Zone:DNS Edit, Zone Read, Tunnel Edit, Access Edit) — held by cf-driver.",
    },
    {
        "key": "SHIMPZ_CF_ACCOUNT",
        "group": "cloudflare",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[0-9a-f]{32}",
        "help": "Cloudflare account ID (32-char hex from the dashboard URL).",
    },
    {
        "key": "SHIMPZ_CF_ZONES",
        "group": "cloudflare",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[a-z0-9.-]+(,[a-z0-9.-]+)*",
        "help": "Comma-separated zones Shimpz manages (optional allowlist).",
    },
    {
        "key": "SHIMPZ_CF_TUNNEL_ID",
        "group": "cloudflare",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[0-9a-f-]{36}",
        "help": "Pin this Space's Tunnel id (needed only when the account owns more than one tunnel).",
    },
    {
        "key": "CF_TUNNEL_TOKEN",
        "group": "cloudflare",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "tunnel_token",
        "help": "Cloudflare Tunnel connector token (Zero Trust → Tunnels). Optional: enables the public desktop.",
    },
    # ── Telegram (the product's voice/text surface) ──────────────────────────────────────────
    {
        "key": "TELEGRAM_BOT_TOKEN",
        "group": "telegram",
        "required": True,
        "generate": False,
        "secret": True,
        "validator": "live_telegram",
        "help": "Bot token from @BotFather.",
    },
    {
        "key": "TELEGRAM_ALLOWED_USERS",
        "group": "telegram",
        "required": True,
        "generate": False,
        "secret": False,
        "validator": "re:\\d+(,\\d+)*",
        "help": "Comma-separated numeric Telegram user IDs allowed to talk to Shimpz (from @userinfobot).",
    },
    # ── OpenAI (voice STT/TTS + imagegen) ────────────────────────────────────────────────────
    {
        "key": "SHIMPZ_OPENAI_MEDIA_API_KEY",
        "group": "openai",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "live_openai",
        "help": "Optional freshly rotated platform media key: powers Telegram voice + imagegen only in "
        "openai-driver; never copy a legacy root OPENAI_API_KEY and never inject it into Brains or Capsules.",
    },
    {
        "key": "VOICE_TOOLS_OPENAI_KEY",
        "group": "openai",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "live_openai",
        "help": "Optional override for separate voice billing; defaults to SHIMPZ_OPENAI_MEDIA_API_KEY.",
    },
    # ── Cloudflare R2 (uploads / links / backup) ─────────────────────────────────────────────
    {
        "key": "R2_ACCOUNT_ID",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[0-9a-f]{32}",
        "help": "R2 account ID (hex, from the S3 endpoint).",
    },
    {
        "key": "R2_ACCESS_KEY_ID",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "re:[0-9a-f]{16,64}",
        "help": "R2 access key (scoped to one bucket).",
    },
    {
        "key": "R2_SECRET_ACCESS_KEY",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": "re:[0-9a-f]{32,128}",
        "help": "R2 secret key.",
    },
    {
        "key": "R2_BUCKET",
        "group": "storage-r2",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[a-z0-9][a-z0-9-]{1,61}[a-z0-9]",
        "help": "Bucket name the token is scoped to.",
    },
    # ── desktop / advanced ───────────────────────────────────────────────────────────────────
    {
        "key": "KASM_USER",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": None,
        "help": "Optional extra basic-auth layer on the KasmVNC desktop.",
    },
    {
        "key": "KASM_PASSWORD",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": True,
        "validator": None,
        "help": "Optional (pairs with KASM_USER).",
    },
    {
        "key": "SHIMPZ_SIGNUP_ENABLED",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[01]",
        "help": "Public signup switch: 1 allows new accounts (default); 0 disables new registrations.",
    },
    {
        "key": "DOCKER_GID",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:\\d{1,6}",
        "help": "Host docker group id (must match `stat -c '%g' /var/run/docker.sock`; default 989).",
    },
    {
        "key": "SHIMPZ_CAPSULE_MAX_HTTP_CONCURRENCY",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[1-9][0-9]*",
        "help": "Maximum simultaneous Capsule control-plane requests (default 64; must be positive).",
    },
    {
        "key": "SHIMPZ_CAPSULE_HTTP_CONNECTION_TIMEOUT_SECONDS",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:[1-9][0-9]*",
        "help": "Capsule control-plane socket timeout in seconds (default 30; must be positive).",
    },
    {
        "key": "SHIMPZ_SUFFIX",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:-[a-z0-9]{1,10}",
        "help": "Multi-instance suffix (e.g. -t) — leave EMPTY on the primary instance. Names every "
        "container/network/volume so two agents coexist on one machine.",
    },
    {
        "key": "SHIMPZ_DATA",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": "re:/[A-Za-z0-9._/-]+",
        "help": "Host data dir bound to /config (default /opt/shimpz; a second instance needs its own, "
        "e.g. /opt/shimpz-t).",
    },
    {
        "key": "CHROME_EXTRA_ARGS",
        "group": "advanced",
        "required": False,
        "generate": False,
        "secret": False,
        "validator": None,
        "help": "Normally empty. Set --no-sandbox only if the host kernel denies user namespaces.",
    },
)

BY_KEY = {f["key"]: f for f in SCHEMA}

# Per-credential acquisition guide — the wizard renders this as an expandable, numbered
# "How to get this →" with a direct link to the provider. Only the credentials a human must
# actually hunt for get an entry; generated/advanced keys rely on their one-line `help`.
GUIDES = {
    "TELEGRAM_BOT_TOKEN": {
        "link": "https://t.me/BotFather",
        "link_label": "Open @BotFather",
        "steps": [
            "In Telegram, open @BotFather and send /newbot.",
            "Choose a display name, then a username ending in “bot”.",
            "Copy the token it replies with — it looks like 123456789:ABCdef… .",
        ],
    },
    "TELEGRAM_ALLOWED_USERS": {
        "link": "https://t.me/userinfobot",
        "link_label": "Open @userinfobot",
        "steps": [
            "In Telegram, open @userinfobot and send any message.",
            "It replies with your numeric ID (e.g. 1529279486).",
            "Paste that number here. Add more IDs comma-separated to allow other people.",
        ],
    },
    "SHIMPZ_OPENAI_MEDIA_API_KEY": {
        "link": "https://platform.openai.com/api-keys",
        "link_label": "OpenAI → API keys",
        "steps": [
            "Sign in at platform.openai.com and open API keys.",
            "Create a new least-privilege media-only secret key and copy the sk-… value.",
            "Never reuse a legacy root OPENAI_API_KEY; remove and rotate that old credential first.",
            "Needed only for Telegram voice (speech-to-text / text-to-speech) and image generation.",
        ],
    },
    "SHIMPZ_CF_ACCOUNT": {
        "link": "https://dash.cloudflare.com/",
        "link_label": "Cloudflare dashboard",
        "steps": [
            "Sign in at dash.cloudflare.com and pick any domain (or Account Home).",
            "Your Account ID is the 32-character hex string in the URL and the right sidebar.",
            "Copy it here.",
        ],
    },
    "SHIMPZ_CF_TOKEN": {
        "link": "https://dash.cloudflare.com/profile/api-tokens",
        "link_label": "Cloudflare → API Tokens",
        "steps": [
            "Open My Profile → API Tokens → Create Token → Create Custom Token.",
            "Add these permissions: Zone → DNS → Edit; Zone → Zone → Read; "
            "Account → Cloudflare Tunnel → Edit; Account → Access: Apps and Policies → Edit.",
            "Under Zone Resources choose All zones (or the specific zones Shimpz manages), then create "
            "and copy the token. This lets Shimpz publish apps on your own domains.",
        ],
    },
    "CF_TUNNEL_TOKEN": {
        "link": "https://one.dash.cloudflare.com/",
        "link_label": "Cloudflare Zero Trust",
        "steps": [
            "In Zero Trust → Networks → Tunnels, create a tunnel (name it “shimpz-brain”).",
            "On the “Install connector” screen, copy the token from the shown command "
            "(the long string after `--token`).",
            "Optional — this is what exposes the live desktop publicly behind Zero Trust Access.",
        ],
    },
    "R2_ACCOUNT_ID": {
        "link": "https://dash.cloudflare.com/?to=/:account/r2",
        "link_label": "Cloudflare → R2",
        "steps": [
            "Open Cloudflare → R2. The Account ID (hex) is shown in the S3 API endpoint.",
            "Create a bucket first if you don’t have one (put its name in R2_BUCKET below).",
            "Optional — R2 is for uploads, share links and backups.",
        ],
    },
    "R2_ACCESS_KEY_ID": {
        "link": "https://dash.cloudflare.com/?to=/:account/r2/api-tokens",
        "link_label": "Cloudflare → R2 → API Tokens",
        "steps": [
            "In R2 → Manage API Tokens, create an Account API token with Object Read & Write, scoped to your bucket.",
            "Copy the Access Key ID here and the Secret Access Key into the next field.",
        ],
    },
}


def field(key):
    """Exact lookup; unknown key raises (the fail-fast contract every caller relies on)."""
    try:
        return BY_KEY[key]
    except KeyError:
        raise ValueError(f"unknown key {key!r} — not in the agent keyset") from None


def generate_internal(existing):
    """Mint values for `generate` keys that are absent/empty in `existing` → {key: new_value}.

    Never overwrites a present value (rotation is a deliberate act, not a side effect).
    """
    return {
        f["key"]: secrets.token_urlsafe(24) for f in SCHEMA if f["generate"] and not existing.get(f["key"], "").strip()
    }
