export const ASSISTANT_ACCOUNTS_COPY = {
  en: {
    trigger: 'Assistant accounts', drawerKicker: 'Assistants // Accounts', drawerTitle: 'Connected accounts',
    drawerLead: 'Only public account and permission status is shown here. Private authorization material never reaches this page.',
    closeDrawer: 'Close accounts', loading: 'Syncing account status…', empty: 'No Assistant declares an external account.',
    pendingTitle: 'This turn needs an account', pendingLead: 'Review every requested permission before continuing to X.',
    connect: 'Connect', connecting: 'Opening X…', disconnect: 'Disconnect', disconnecting: 'Disconnecting…',
    provider: 'Provider', account: 'Account', scopes: 'Permissions', noAccount: 'Not connected',
    statusMissing: 'Missing', statusConnected: 'Connected', statusExpired: 'Expired', statusReauthorization: 'Reconnect required',
    dialogKicker: 'Power batch // Accounts', dialogTitle: 'Connect required accounts',
    dialogLead: 'The paused Powers can continue only after you authorize these permissions directly on X.',
    powers: 'Used by Powers', scopesTitle: 'Requested permissions', cancel: 'Close', authorize: 'Continue to X',
    authorizing: 'Opening X…', authorizationFailed: 'The secure authorization could not start.',
    inventoryFailed: 'Account status is unavailable.', disconnectFailed: 'The account could not be disconnected.',
  },
  pt: {
    trigger: 'Contas dos Assistants', drawerKicker: 'Assistants // Contas', drawerTitle: 'Contas conectadas',
    drawerLead: 'Somente a conta pública e o estado das permissões aparecem aqui. O material privado de autorização nunca chega a esta página.',
    closeDrawer: 'Fechar contas', loading: 'Sincronizando contas…', empty: 'Nenhum Assistant declara uma conta externa.',
    pendingTitle: 'Este turno precisa de uma conta', pendingLead: 'Revise todas as permissões solicitadas antes de continuar no X.',
    connect: 'Conectar', connecting: 'Abrindo o X…', disconnect: 'Desconectar', disconnecting: 'Desconectando…',
    provider: 'Provedor', account: 'Conta', scopes: 'Permissões', noAccount: 'Não conectada',
    statusMissing: 'Ausente', statusConnected: 'Conectada', statusExpired: 'Expirada', statusReauthorization: 'Reconexão necessária',
    dialogKicker: 'Lote de Powers // Contas', dialogTitle: 'Conecte as contas necessárias',
    dialogLead: 'Os Powers pausados só podem continuar depois que você autorizar estas permissões diretamente no X.',
    powers: 'Usada pelos Powers', scopesTitle: 'Permissões solicitadas', cancel: 'Fechar', authorize: 'Continuar no X',
    authorizing: 'Abrindo o X…', authorizationFailed: 'Não foi possível iniciar a autorização segura.',
    inventoryFailed: 'O estado das contas está indisponível.', disconnectFailed: 'Não foi possível desconectar a conta.',
  },
  es: {
    trigger: 'Cuentas de Assistants', drawerKicker: 'Assistants // Cuentas', drawerTitle: 'Cuentas conectadas',
    drawerLead: 'Aquí solo se muestran la cuenta pública y el estado de los permisos. El material privado de autorización nunca llega a esta página.',
    closeDrawer: 'Cerrar cuentas', loading: 'Sincronizando cuentas…', empty: 'Ningún Assistant declara una cuenta externa.',
    pendingTitle: 'Este turno necesita una cuenta', pendingLead: 'Revisa todos los permisos solicitados antes de continuar en X.',
    connect: 'Conectar', connecting: 'Abriendo X…', disconnect: 'Desconectar', disconnecting: 'Desconectando…',
    provider: 'Proveedor', account: 'Cuenta', scopes: 'Permisos', noAccount: 'No conectada',
    statusMissing: 'Falta', statusConnected: 'Conectada', statusExpired: 'Caducada', statusReauthorization: 'Se requiere reconexión',
    dialogKicker: 'Lote de Powers // Cuentas', dialogTitle: 'Conecta las cuentas necesarias',
    dialogLead: 'Los Powers pausados solo pueden continuar después de autorizar estos permisos directamente en X.',
    powers: 'Usada por Powers', scopesTitle: 'Permisos solicitados', cancel: 'Cerrar', authorize: 'Continuar en X',
    authorizing: 'Abriendo X…', authorizationFailed: 'No se pudo iniciar la autorización segura.',
    inventoryFailed: 'El estado de las cuentas no está disponible.', disconnectFailed: 'No se pudo desconectar la cuenta.',
  },
  zh: {
    trigger: 'Assistant 账户', drawerKicker: 'Assistants // 账户', drawerTitle: '已连接账户',
    drawerLead: '此处仅显示公开账户与权限状态，私密授权材料绝不会到达此页面。',
    closeDrawer: '关闭账户', loading: '正在同步账户状态…', empty: '没有 Assistant 声明外部账户。',
    pendingTitle: '本轮需要一个账户', pendingLead: '继续前往 X 前，请检查所有请求的权限。',
    connect: '连接', connecting: '正在打开 X…', disconnect: '断开连接', disconnecting: '正在断开…',
    provider: '提供方', account: '账户', scopes: '权限', noAccount: '未连接',
    statusMissing: '缺失', statusConnected: '已连接', statusExpired: '已过期', statusReauthorization: '需要重新连接',
    dialogKicker: 'Power 批次 // 账户', dialogTitle: '连接所需账户',
    dialogLead: '只有在 X 上直接授权这些权限后，暂停的 Powers 才能继续。',
    powers: '使用这些权限的 Powers', scopesTitle: '请求的权限', cancel: '关闭', authorize: '继续前往 X',
    authorizing: '正在打开 X…', authorizationFailed: '无法启动安全授权。',
    inventoryFailed: '账户状态不可用。', disconnectFailed: '无法断开账户连接。',
  },
  fr: {
    trigger: 'Comptes des Assistants', drawerKicker: 'Assistants // Comptes', drawerTitle: 'Comptes connectés',
    drawerLead: 'Seuls le compte public et l’état des autorisations sont affichés. Le matériel privé d’autorisation n’atteint jamais cette page.',
    closeDrawer: 'Fermer les comptes', loading: 'Synchronisation des comptes…', empty: 'Aucun Assistant ne déclare de compte externe.',
    pendingTitle: 'Ce tour nécessite un compte', pendingLead: 'Vérifiez toutes les autorisations demandées avant de continuer sur X.',
    connect: 'Connecter', connecting: 'Ouverture de X…', disconnect: 'Déconnecter', disconnecting: 'Déconnexion…',
    provider: 'Fournisseur', account: 'Compte', scopes: 'Autorisations', noAccount: 'Non connecté',
    statusMissing: 'Manquant', statusConnected: 'Connecté', statusExpired: 'Expiré', statusReauthorization: 'Reconnexion requise',
    dialogKicker: 'Lot de Powers // Comptes', dialogTitle: 'Connectez les comptes requis',
    dialogLead: 'Les Powers en pause ne peuvent continuer qu’après votre autorisation directe de ces permissions sur X.',
    powers: 'Utilisée par les Powers', scopesTitle: 'Autorisations demandées', cancel: 'Fermer', authorize: 'Continuer sur X',
    authorizing: 'Ouverture de X…', authorizationFailed: 'Impossible de lancer l’autorisation sécurisée.',
    inventoryFailed: 'L’état des comptes est indisponible.', disconnectFailed: 'Impossible de déconnecter le compte.',
  },
  de: {
    trigger: 'Assistant-Konten', drawerKicker: 'Assistants // Konten', drawerTitle: 'Verbundene Konten',
    drawerLead: 'Hier werden nur das öffentliche Konto und der Berechtigungsstatus angezeigt. Privates Autorisierungsmaterial erreicht diese Seite nie.',
    closeDrawer: 'Konten schließen', loading: 'Kontostatus wird synchronisiert…', empty: 'Kein Assistant deklariert ein externes Konto.',
    pendingTitle: 'Diese Runde benötigt ein Konto', pendingLead: 'Prüfe alle angeforderten Berechtigungen, bevor du auf X fortfährst.',
    connect: 'Verbinden', connecting: 'X wird geöffnet…', disconnect: 'Trennen', disconnecting: 'Verbindung wird getrennt…',
    provider: 'Anbieter', account: 'Konto', scopes: 'Berechtigungen', noAccount: 'Nicht verbunden',
    statusMissing: 'Fehlt', statusConnected: 'Verbunden', statusExpired: 'Abgelaufen', statusReauthorization: 'Erneute Verbindung nötig',
    dialogKicker: 'Power-Stapel // Konten', dialogTitle: 'Erforderliche Konten verbinden',
    dialogLead: 'Die pausierten Powers können erst fortfahren, nachdem du diese Berechtigungen direkt auf X autorisiert hast.',
    powers: 'Verwendet von Powers', scopesTitle: 'Angeforderte Berechtigungen', cancel: 'Schließen', authorize: 'Weiter zu X',
    authorizing: 'X wird geöffnet…', authorizationFailed: 'Die sichere Autorisierung konnte nicht gestartet werden.',
    inventoryFailed: 'Der Kontostatus ist nicht verfügbar.', disconnectFailed: 'Das Konto konnte nicht getrennt werden.',
  },
  ja: {
    trigger: 'Assistant のアカウント', drawerKicker: 'Assistants // アカウント', drawerTitle: '接続済みアカウント',
    drawerLead: 'ここには公開アカウントと権限の状態だけが表示され、非公開の認証情報が届くことはありません。',
    closeDrawer: 'アカウントを閉じる', loading: 'アカウント状態を同期中…', empty: '外部アカウントを宣言している Assistant はありません。',
    pendingTitle: 'このターンにはアカウントが必要です', pendingLead: 'X に進む前に、要求されたすべての権限を確認してください。',
    connect: '接続', connecting: 'X を開いています…', disconnect: '切断', disconnecting: '切断中…',
    provider: 'プロバイダー', account: 'アカウント', scopes: '権限', noAccount: '未接続',
    statusMissing: '未設定', statusConnected: '接続済み', statusExpired: '期限切れ', statusReauthorization: '再接続が必要',
    dialogKicker: 'Power バッチ // アカウント', dialogTitle: '必要なアカウントを接続',
    dialogLead: 'X 上でこれらの権限を直接許可した後にのみ、一時停止中の Powers を続行できます。',
    powers: '使用する Powers', scopesTitle: '要求された権限', cancel: '閉じる', authorize: 'X に進む',
    authorizing: 'X を開いています…', authorizationFailed: '安全な認証を開始できませんでした。',
    inventoryFailed: 'アカウント状態を取得できません。', disconnectFailed: 'アカウントを切断できませんでした。',
  },
  ar: {
    trigger: 'حسابات Assistants', drawerKicker: 'Assistants // الحسابات', drawerTitle: 'الحسابات المتصلة',
    drawerLead: 'يُعرض هنا الحساب العام وحالة الصلاحيات فقط، ولا تصل مواد التفويض الخاصة إلى هذه الصفحة مطلقًا.',
    closeDrawer: 'إغلاق الحسابات', loading: 'جارٍ مزامنة حالة الحسابات…', empty: 'لا يعلن أي Assistant عن حساب خارجي.',
    pendingTitle: 'تحتاج هذه الجولة إلى حساب', pendingLead: 'راجع كل الصلاحيات المطلوبة قبل المتابعة إلى X.',
    connect: 'اتصال', connecting: 'جارٍ فتح X…', disconnect: 'قطع الاتصال', disconnecting: 'جارٍ قطع الاتصال…',
    provider: 'المزوّد', account: 'الحساب', scopes: 'الصلاحيات', noAccount: 'غير متصل',
    statusMissing: 'مفقود', statusConnected: 'متصل', statusExpired: 'منتهي', statusReauthorization: 'إعادة الاتصال مطلوبة',
    dialogKicker: 'دفعة Powers // الحسابات', dialogTitle: 'صِل الحسابات المطلوبة',
    dialogLead: 'لا يمكن متابعة Powers المتوقفة إلا بعد تفويض هذه الصلاحيات مباشرةً على X.',
    powers: 'تستخدمها Powers', scopesTitle: 'الصلاحيات المطلوبة', cancel: 'إغلاق', authorize: 'المتابعة إلى X',
    authorizing: 'جارٍ فتح X…', authorizationFailed: 'تعذر بدء التفويض الآمن.',
    inventoryFailed: 'حالة الحسابات غير متاحة.', disconnectFailed: 'تعذر قطع اتصال الحساب.',
  },
};

export function assistantAccountsCopy(locale) {
  return ASSISTANT_ACCOUNTS_COPY[locale] ?? ASSISTANT_ACCOUNTS_COPY.en;
}
