export const ASSISTANT_SECRETS_COPY = {
  en: {
    trigger: 'Assistant secrets',
    drawerKicker: 'Assistants // Secrets',
    drawerTitle: 'Secret inventory',
    drawerLead: 'Only public metadata is shown here. Values are never displayed again.',
    closeDrawer: 'Close secrets',
    loading: 'Syncing secret metadata…',
    noAssistants: 'No Assistants are installed in this Team.',
    noSecrets: 'This Assistant declares no secrets.',
    configured: 'Configured',
    missing: 'Missing',
    mask: 'Saved value',
    pendingTitle: 'This turn needs secrets',
    pendingLead: 'Add every missing value to continue the paused Power batch.',
    provide: 'Add missing secrets',
    dialogKicker: 'Power batch // Secrets',
    dialogTitle: 'Add required secrets',
    dialogLead: 'These values go directly to the local Team controller. They are never added to the chat or Brain prompt.',
    powers: 'Required by Powers',
    value: 'Secret value',
    placeholder: 'Paste the secret value',
    privacy: 'Values stay in this dialog only until they are submitted or you close it.',
    cancel: 'Close',
    submit: 'Save and continue',
    submitting: 'Submitting…',
    submitFailed: 'The secrets could not be submitted. All entered values were cleared.',
  },
  pt: {
    trigger: 'Segredos dos Assistants',
    drawerKicker: 'Assistants // Segredos',
    drawerTitle: 'Inventário de segredos',
    drawerLead: 'Apenas metadados públicos aparecem aqui. Os valores nunca são exibidos novamente.',
    closeDrawer: 'Fechar segredos',
    loading: 'Sincronizando metadados dos segredos…',
    noAssistants: 'Nenhum Assistant está instalado neste Time.',
    noSecrets: 'Este Assistant não declara segredos.',
    configured: 'Configurado',
    missing: 'Ausente',
    mask: 'Valor salvo',
    pendingTitle: 'Este turno precisa de segredos',
    pendingLead: 'Adicione todos os valores ausentes para continuar o lote de Powers pausado.',
    provide: 'Adicionar segredos ausentes',
    dialogKicker: 'Lote de Powers // Segredos',
    dialogTitle: 'Adicione os segredos necessários',
    dialogLead: 'Esses valores vão direto ao controller local do Time. Eles nunca entram no chat nem no prompt do Brain.',
    powers: 'Exigido pelos Powers',
    value: 'Valor secreto',
    placeholder: 'Cole o valor secreto',
    privacy: 'Os valores ficam somente nesta janela até o envio ou até você fechá-la.',
    cancel: 'Fechar',
    submit: 'Salvar e continuar',
    submitting: 'Enviando…',
    submitFailed: 'Não foi possível enviar os segredos. Todos os valores digitados foram apagados.',
  },
  es: {
    trigger: 'Secretos de Assistants',
    drawerKicker: 'Assistants // Secretos',
    drawerTitle: 'Inventario de secretos',
    drawerLead: 'Aquí solo se muestran metadatos públicos. Los valores nunca vuelven a mostrarse.',
    closeDrawer: 'Cerrar secretos',
    loading: 'Sincronizando metadatos de secretos…',
    noAssistants: 'No hay Assistants instalados en este Equipo.',
    noSecrets: 'Este Assistant no declara secretos.',
    configured: 'Configurado',
    missing: 'Falta',
    mask: 'Valor guardado',
    pendingTitle: 'Este turno necesita secretos',
    pendingLead: 'Añade todos los valores que faltan para continuar el lote de Powers pausado.',
    provide: 'Añadir secretos faltantes',
    dialogKicker: 'Lote de Powers // Secretos',
    dialogTitle: 'Añade los secretos necesarios',
    dialogLead: 'Estos valores van directamente al controlador local del Equipo. Nunca se añaden al chat ni al prompt del Brain.',
    powers: 'Requerido por los Powers',
    value: 'Valor secreto',
    placeholder: 'Pega el valor secreto',
    privacy: 'Los valores permanecen solo en este diálogo hasta enviarlos o cerrarlo.',
    cancel: 'Cerrar',
    submit: 'Guardar y continuar',
    submitting: 'Enviando…',
    submitFailed: 'No se pudieron enviar los secretos. Se borraron todos los valores introducidos.',
  },
  zh: {
    trigger: 'Assistant 密钥',
    drawerKicker: 'Assistants // 密钥',
    drawerTitle: '密钥清单',
    drawerLead: '此处仅显示公开元数据，密钥值不会再次显示。',
    closeDrawer: '关闭密钥面板',
    loading: '正在同步密钥元数据…',
    noAssistants: '此团队尚未安装 Assistant。',
    noSecrets: '此 Assistant 未声明密钥。',
    configured: '已配置',
    missing: '缺失',
    mask: '已保存的值',
    pendingTitle: '此轮需要密钥',
    pendingLead: '请添加所有缺失值，以继续暂停的 Power 批次。',
    provide: '添加缺失密钥',
    dialogKicker: 'Power 批次 // 密钥',
    dialogTitle: '添加所需密钥',
    dialogLead: '这些值会直接发送到本地团队控制器，绝不会加入聊天或 Brain 提示词。',
    powers: '所需的 Powers',
    value: '密钥值',
    placeholder: '粘贴密钥值',
    privacy: '这些值仅在此对话框中保留，提交或关闭后即清除。',
    cancel: '关闭',
    submit: '保存并继续',
    submitting: '正在提交…',
    submitFailed: '无法提交密钥。所有已输入的值均已清除。',
  },
  fr: {
    trigger: 'Secrets des Assistants',
    drawerKicker: 'Assistants // Secrets',
    drawerTitle: 'Inventaire des secrets',
    drawerLead: 'Seules les métadonnées publiques sont affichées. Les valeurs ne sont jamais réaffichées.',
    closeDrawer: 'Fermer les secrets',
    loading: 'Synchronisation des métadonnées…',
    noAssistants: 'Aucun Assistant n’est installé dans cette Équipe.',
    noSecrets: 'Cet Assistant ne déclare aucun secret.',
    configured: 'Configuré',
    missing: 'Manquant',
    mask: 'Valeur enregistrée',
    pendingTitle: 'Ce tour nécessite des secrets',
    pendingLead: 'Ajoutez toutes les valeurs manquantes pour reprendre le lot de Powers en pause.',
    provide: 'Ajouter les secrets manquants',
    dialogKicker: 'Lot de Powers // Secrets',
    dialogTitle: 'Ajoutez les secrets requis',
    dialogLead: 'Ces valeurs vont directement au contrôleur local de l’Équipe. Elles ne sont jamais ajoutées au chat ni au prompt du Brain.',
    powers: 'Requis par les Powers',
    value: 'Valeur secrète',
    placeholder: 'Collez la valeur secrète',
    privacy: 'Les valeurs restent uniquement dans cette fenêtre jusqu’à leur envoi ou sa fermeture.',
    cancel: 'Fermer',
    submit: 'Enregistrer et continuer',
    submitting: 'Envoi…',
    submitFailed: 'Impossible d’envoyer les secrets. Toutes les valeurs saisies ont été effacées.',
  },
  de: {
    trigger: 'Assistant-Secrets',
    drawerKicker: 'Assistants // Secrets',
    drawerTitle: 'Secret-Inventar',
    drawerLead: 'Hier werden nur öffentliche Metadaten angezeigt. Werte werden nie wieder eingeblendet.',
    closeDrawer: 'Secrets schließen',
    loading: 'Secret-Metadaten werden synchronisiert…',
    noAssistants: 'In diesem Team sind keine Assistants installiert.',
    noSecrets: 'Dieser Assistant deklariert keine Secrets.',
    configured: 'Konfiguriert',
    missing: 'Fehlt',
    mask: 'Gespeicherter Wert',
    pendingTitle: 'Diese Runde benötigt Secrets',
    pendingLead: 'Füge alle fehlenden Werte hinzu, um den pausierten Power-Stapel fortzusetzen.',
    provide: 'Fehlende Secrets hinzufügen',
    dialogKicker: 'Power-Stapel // Secrets',
    dialogTitle: 'Erforderliche Secrets hinzufügen',
    dialogLead: 'Diese Werte gehen direkt an den lokalen Team-Controller. Sie werden nie dem Chat oder Brain-Prompt hinzugefügt.',
    powers: 'Benötigt von Powers',
    value: 'Secret-Wert',
    placeholder: 'Secret-Wert einfügen',
    privacy: 'Werte bleiben nur bis zum Senden oder Schließen in diesem Dialog.',
    cancel: 'Schließen',
    submit: 'Speichern und fortfahren',
    submitting: 'Wird gesendet…',
    submitFailed: 'Die Secrets konnten nicht gesendet werden. Alle eingegebenen Werte wurden gelöscht.',
  },
  ja: {
    trigger: 'Assistant のシークレット',
    drawerKicker: 'Assistants // シークレット',
    drawerTitle: 'シークレット一覧',
    drawerLead: 'ここには公開メタデータのみ表示され、値が再表示されることはありません。',
    closeDrawer: 'シークレットを閉じる',
    loading: 'シークレットのメタデータを同期中…',
    noAssistants: 'このチームには Assistant がインストールされていません。',
    noSecrets: 'この Assistant はシークレットを宣言していません。',
    configured: '設定済み',
    missing: '未設定',
    mask: '保存済みの値',
    pendingTitle: 'このターンにはシークレットが必要です',
    pendingLead: '一時停止中の Power バッチを続行するには、不足している値をすべて追加してください。',
    provide: '不足しているシークレットを追加',
    dialogKicker: 'Power バッチ // シークレット',
    dialogTitle: '必要なシークレットを追加',
    dialogLead: '値はローカルのチームコントローラーへ直接送られ、チャットや Brain のプロンプトには追加されません。',
    powers: '必要とする Powers',
    value: 'シークレット値',
    placeholder: 'シークレット値を貼り付け',
    privacy: '値は送信または閉じるまで、このダイアログ内だけに保持されます。',
    cancel: '閉じる',
    submit: '保存して続行',
    submitting: '送信中…',
    submitFailed: 'シークレットを送信できませんでした。入力した値はすべて消去されました。',
  },
  ar: {
    trigger: 'أسرار Assistants',
    drawerKicker: 'Assistants // الأسرار',
    drawerTitle: 'قائمة الأسرار',
    drawerLead: 'تُعرض هنا البيانات الوصفية العامة فقط، ولا تُعرض القيم مرة أخرى.',
    closeDrawer: 'إغلاق الأسرار',
    loading: 'جارٍ مزامنة بيانات الأسرار…',
    noAssistants: 'لا يوجد Assistant مثبّت في هذا الفريق.',
    noSecrets: 'لا يعلن هذا الـ Assistant أي أسرار.',
    configured: 'مُعدّ',
    missing: 'مفقود',
    mask: 'القيمة المحفوظة',
    pendingTitle: 'تحتاج هذه الجولة إلى أسرار',
    pendingLead: 'أضف كل القيم المفقودة لمتابعة دفعة Powers المتوقفة.',
    provide: 'إضافة الأسرار المفقودة',
    dialogKicker: 'دفعة Powers // الأسرار',
    dialogTitle: 'أضف الأسرار المطلوبة',
    dialogLead: 'تذهب هذه القيم مباشرةً إلى متحكم الفريق المحلي، ولا تُضاف مطلقًا إلى المحادثة أو موجّه Brain.',
    powers: 'مطلوبة بواسطة Powers',
    value: 'القيمة السرية',
    placeholder: 'الصق القيمة السرية',
    privacy: 'تبقى القيم داخل هذه النافذة فقط حتى إرسالها أو إغلاقها.',
    cancel: 'إغلاق',
    submit: 'حفظ ومتابعة',
    submitting: 'جارٍ الإرسال…',
    submitFailed: 'تعذر إرسال الأسرار. تم مسح جميع القيم المُدخلة.',
  },
};

export function assistantSecretsCopy(locale) {
  return ASSISTANT_SECRETS_COPY[locale] ?? ASSISTANT_SECRETS_COPY.en;
}
